# Generated by Django 5.2.17 on 2026-09-12 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('HANDLE NOW', 'Handle Now (Collection Required)'), ('HANDLE LATER', 'Handle Later'), ('INSPECT', 'Inspect Waste Container'), ('ISOLATE', 'Isolate Container Immediately'), ('MECHANICALLY TRANSFER', 'Mechanically Transfer'), ('SPECIALIST REQUIRED', 'Biomedical Specialist Required'), ('CLEAN / MAINTENANCE', 'Clean / Sensor Maintenance'), ('NO ACTION', 'No Action Required')], default='HANDLE LATER', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Priority')], default='LOW', max_length=20)),
                ('reason', models.TextField(help_text='Reason for recommended action')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to=settings.AUTH_USER_MODEL)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='containers.container')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
