# Generated by Django 5.2.17 on 2026-09-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Severity')], default='WARNING', max_length=20)),
                ('alert_type', models.CharField(choices=[('HIGH_RISK', 'High Operational Risk'), ('CRITICAL_RISK', 'Critical Biohazard Risk'), ('OVERFILLED', 'Container Overfilled'), ('ABNORMAL_TEMP', 'Abnormal Temperature'), ('GAS_ANOMALY', 'Toxic / Gas VOC Anomaly'), ('MOISTURE_ANOMALY', 'Liquid Bio-Spill / Moisture Anomaly'), ('AI_UNCERTAINTY', 'AI Classification Uncertainty'), ('SENSOR_FAILURE', 'Sensor Malfunction'), ('DEVICE_OFFLINE', 'Device Disconnected'), ('MECHANICAL_FAILURE', 'Mechanical System Error')], default='HIGH_RISK', max_length=30)),
                ('message', models.TextField(help_text='Alert summary message')),
                ('recommended_action', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='containers.container')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
