# Generated by Django 5.2.17 on 2026-09-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('predicted_class', models.CharField(choices=[('NORMAL', 'Normal Waste'), ('BIOHAZARD', 'Biohazardous Material'), ('SHARPS', 'Sharps / Needles'), ('HAZARD', 'Chemical / Dangerous Hazard'), ('UNKNOWN', 'Unknown / Low Confidence')], default='NORMAL', max_length=30)),
                ('confidence', models.FloatField(help_text='AI Classification confidence 0.0 - 100.0%')),
                ('contamination_score', models.FloatField(default=0.0, help_text='Estimated cross-contamination likelihood 0-100%')),
                ('unknown_probability', models.FloatField(default=0.0, help_text='Uncertainty / Out-of-distribution probability 0-100%')),
                ('exception_reason', models.TextField(blank=True, help_text='Note on potential abnormal condition or anomaly', null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_events', to='containers.container')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
