# Generated by Django 5.2.17 on 2026-09-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('risk_score', models.IntegerField(help_text='Calculated risk score 0 to 100')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=20)),
                ('recommended_action', models.CharField(help_text='Operational action recommendation', max_length=50)),
                ('reason', models.TextField(help_text='Detailed clinical and sensor rationale for recommendation')),
                ('model_version', models.CharField(default='RiskEngine-v1.2-RuleSystem', max_length=30)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='containers.container')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
