# Generated by Django 5.2.17 on 2026-09-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('fill_level', models.FloatField(help_text='Fill level percentage 0-100%')),
                ('temperature', models.FloatField(help_text='Temperature in degrees Celsius')),
                ('humidity', models.FloatField(help_text='Relative humidity percentage')),
                ('gas_indicator', models.FloatField(help_text='VOC gas sensor reading in ppm or raw index')),
                ('moisture', models.FloatField(help_text='Moisture sensor percentage 0-100%')),
                ('device_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=20)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='containers.container')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
