# Generated by Django 5.2.17 on 2026-09-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('hospital', models.CharField(default='City Central Hospital', max_length=150)),
                ('location', models.CharField(help_text='Specific location room or corridor', max_length=150)),
                ('ward', models.CharField(db_index=True, help_text='Ward / Department (e.g. ICU, Emergency Ward, Surgery)', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('capacity_liters', models.FloatField(default=60.0)),
                ('device_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=20)),
                ('waste_category', models.CharField(choices=[('GENERAL', 'General Non-Hazardous'), ('INFECTIOUS', 'Infectious Biomedical'), ('SHARPS', 'Sharps Waste'), ('HAZARDOUS', 'Chemical / Hazardous'), ('CYTOTOXIC', 'Cytotoxic Waste'), ('ANATOMICAL', 'Anatomical Waste')], default='INFECTIOUS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['container_id'],
            },
        ),
    ]
